Name:           ros-jade-ompl-visual-tools
Version:        2.3.1
Release:        0%{?dist}
Summary:        ROS ompl_visual_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ompl_visual_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-graph-msgs
Requires:       ros-jade-moveit-core
Requires:       ros-jade-moveit-planners-ompl
Requires:       ros-jade-moveit-visual-tools
Requires:       ros-jade-ompl >= 0.14.0
Requires:       ros-jade-roscpp
Requires:       ros-jade-roslib
Requires:       ros-jade-visualization-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-graph-msgs
BuildRequires:  ros-jade-moveit-core
BuildRequires:  ros-jade-moveit-planners-ompl
BuildRequires:  ros-jade-moveit-visual-tools
BuildRequires:  ros-jade-ompl >= 0.14.0
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roslib
BuildRequires:  ros-jade-visualization-msgs

%description
Rviz 3-D visualizer for planning algorithms implemented with the Open Motion
Planning Library (OMPL)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Dec 10 2015 Dave Coleman <davetcoleman@gmail.com> - 2.3.1-0
- Autogenerated by Bloom

